---
# @action Ensures Java is installed
# Installs Java using Chocolatey on Windows
- name: Install Java
  chocolatey.chocolatey.win_chocolatey:
    name: jre8
    state: present

# @action Windows optimization
# Removes Java folder from the start menu on Windows
- name: Remove Java folder from start menu
  include_role:
    name: startmenu
